import { default as QAvator } from './components/Avator.vue';
import { default as QBadge } from './components/Badge.vue';
import { default as QCarousel } from './components/Carousel.vue';
import { default as QCarouselItem } from './components/CarouselItem.vue';
import { default as QCollapsibleSection } from './components/CollapsibleSection.vue';
import { default as QDivider } from './components/Divider.vue';
import { default as QIcon } from './components/Icon.vue';
import { default as QIconGroups } from './components/IconGroups.vue';
import { default as QMarkdownRender } from './components/MarkdownRender.vue';
import { default as QMobileFrame } from './components/MobileFrame.vue';
import { default as QNavSection } from './components/NavSection.vue';
import { default as QProgressBar } from './components/ProgressBar.vue';
import { default as QRainFigure } from './components/RainFigure.vue';
import { default as QScrollNotice } from './components/ScrollNotice.vue';
import { default as QSearch } from './components/Search.vue';
import { default as QTabList } from './components/TabList.vue';
import { default as QTag } from './components/Tag.vue';
import { default as QThemeToggle } from './components/ThemeToggle.vue';
import { default as QTypeText } from './components/TypeText.vue';
import { default as QCard } from './layout/Card.vue';
import { default as QScollContainer } from './layout/ScollContainer.vue';
import { type App } from 'vue';
declare const _default: {
    install(app: App): void;
};
export default _default;
export { QAvator, QBadge, QCarousel, QCarouselItem, QCollapsibleSection, QDivider, QIcon, QIconGroups, QMarkdownRender, QMobileFrame, QNavSection, QProgressBar, QRainFigure, QScrollNotice, QSearch, QTabList, QTag, QThemeToggle, QTypeText, QCard, QScollContainer, };
