import './style/common.css';
import './style/private.css';
export * from './events';
export * from './utils';
export * from './types';
export * from './components/basic/Icon';
export * from './components/basic/Message';
export * from './components/basic/Pagination';
export * from './components/basic/Tag';
export * from './components/display/Avatar';
export * from './components/display/Badge';
export * from './components/display/Carousel';
export * from './components/display/MarkdownRender';
export * from './components/display/ProgressBar';
export * from './components/display/ScrollNotice';
export * from './components/loading/Loading';
export * from './components/layout/Card';
export * from './components/layout/Collapse';
export * from './components/layout/CollapseItem';
export * from './components/layout/CollapsibleSection';
export * from './components/layout/Dialog';
export * from './components/layout/Drawer';
export * from './components/layout/PopContainer';
export * from './components/layout/ScrollContainer';
export * from './components/layout/SwiperAction';
export * from './components/layout/Tree';
export * from './components/layout/TreeNode';
export * from './components/navigation/NavSection';
export * from './components/navigation/Tab';
export * from './components/theme/ThemeToggle';
import { QIcon } from './components/basic/Icon';
import { QMessage } from './components/basic/Message';
import { QPagination } from './components/basic/Pagination';
import { QTag } from './components/basic/Tag';
import { QAvatar } from './components/display/Avatar';
import { QBadge } from './components/display/Badge';
import { QCarousel } from './components/display/Carousel';
import { QCarouselItem } from './components/display/CarouselItem';
import { QDivider } from './components/display/Divider';
import { QLazyImage } from './components/display/LazyImage';
import { QMarkdownRender } from './components/display/MarkdownRender';
import { QProgressBar } from './components/display/ProgressBar';
import { QScrollNotice } from './components/display/ScrollNotice';
export * from './components/form/FormButton';
export * from './components/form/FormCheckboxGroup';
export * from './components/form/FormColorPicker';
export * from './components/form/FormDatePicker';
export * from './components/form/FormFileUpload';
export * from './components/form/FormRadioGroup';
export * from './components/form/FormRangeSlider';
export * from './components/form/FormSelect';
export * from './components/form/FormSwitch';
export * from './components/form/FormTable';
export * from './components/form/FormText';
export * from './components/form/FormTextarea';
export * from './components/form/Search';
import { QFormButton } from './components/form/FormButton';
import { QFormCheckboxGroup } from './components/form/FormCheckboxGroup';
import { QFormColorPicker } from './components/form/FormColorPicker';
import { QFormDatePicker } from './components/form/FormDatePicker';
import { QFormFileUpload } from './components/form/FormFileUpload';
import { QFormRadioGroup } from './components/form/FormRadioGroup';
import { QFormRangeSlider } from './components/form/FormRangeSlider';
import { QFormSelect } from './components/form/FormSelect';
import { QFormSwitch } from './components/form/FormSwitch';
import { QFormTable } from './components/form/FormTable';
import { QFormText } from './components/form/FormText';
import { QFormTextarea } from './components/form/FormTextarea';
import { QSearch } from './components/form/Search';
import { QCard } from './components/layout/Card';
import { QCollapse } from './components/layout/Collapse';
import { QCollapseItem } from './components/layout/CollapseItem';
import { QCollapsibleSection } from './components/layout/CollapsibleSection';
import { QDialog } from './components/layout/Dialog';
import { QDrawer } from './components/layout/Drawer';
import { QPopContainer } from './components/layout/PopContainer';
import { QScrollContainer } from './components/layout/ScrollContainer';
import { QSwiperAction } from './components/layout/SwiperAction';
import { QTree } from './components/layout/Tree';
import { QTreeNode } from './components/layout/TreeNode';
import { QLoading } from './components/loading/Loading';
import {
  QBreathing,
  QSkeleton,
  QSpinner,
} from './components/loading/animations';
import { QNavSection } from './components/navigation/NavSection';
import { QTab } from './components/navigation/Tab';
import { QThemeToggle } from './components/theme/ThemeToggle';
export default {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  install(app: any) {
    app.component('QIcon', QIcon);
    app.component('QMessage', QMessage);
    app.component('QPagination', QPagination);
    app.component('QTag', QTag);
    app.component('QAvatar', QAvatar);
    app.component('QBadge', QBadge);
    app.component('QCarousel', QCarousel);
    app.component('QCarouselItem', QCarouselItem);
    app.component('QDivider', QDivider);
    app.component('QLazyImage', QLazyImage);
    app.component('QMarkdownRender', QMarkdownRender);
    app.component('QProgressBar', QProgressBar);
    app.component('QScrollNotice', QScrollNotice);
    app.component('QFormButton', QFormButton);
    app.component('QFormCheckboxGroup', QFormCheckboxGroup);
    app.component('QFormColorPicker', QFormColorPicker);
    app.component('QFormDatePicker', QFormDatePicker);
    app.component('QFormFileUpload', QFormFileUpload);
    app.component('QFormRadioGroup', QFormRadioGroup);
    app.component('QFormRangeSlider', QFormRangeSlider);
    app.component('QFormSelect', QFormSelect);
    app.component('QFormSwitch', QFormSwitch);
    app.component('QFormTable', QFormTable);
    app.component('QFormText', QFormText);
    app.component('QFormTextarea', QFormTextarea);
    app.component('QSearch', QSearch);
    app.component('QCard', QCard);
    app.component('QCollapse', QCollapse);
    app.component('QCollapseItem', QCollapseItem);
    app.component('QCollapsibleSection', QCollapsibleSection);
    app.component('QDialog', QDialog);
    app.component('QDrawer', QDrawer);
    app.component('QPopContainer', QPopContainer);
    app.component('QScrollContainer', QScrollContainer);
    app.component('QSwiperAction', QSwiperAction);
    app.component('QTree', QTree);
    app.component('QTreeNode', QTreeNode);
    app.component('QLoading', QLoading);
    app.component('QBreathing', QBreathing);
    app.component('QSkeleton', QSkeleton);
    app.component('QSpinner', QSpinner);
    app.component('QNavSection', QNavSection);
    app.component('QTab', QTab);
    app.component('QThemeToggle', QThemeToggle);
  },
};
