import type { App } from 'vue';

import { QButton } from './components/basic/Button';
import { QFloatButton } from './components/basic/FloatButton';
import { QIcon } from './components/basic/Icon';
import { QMessage } from './components/basic/Message';
import { QNotification } from './components/basic/Notification';
import { QPagination } from './components/basic/Pagination';
import { QTag } from './components/basic/Tag';
import { QTypography } from './components/basic/Typography';
import { QAlert } from './components/display/Alert';
import { QAvatar } from './components/display/Avatar';
import { QBadge } from './components/display/Badge';
import { QBorderBeam } from './components/display/BorderBeam';
import { QCalendar } from './components/display/Calendar';
import { QCarousel } from './components/display/Carousel';
import { QCarouselItem } from './components/display/CarouselItem';
import { QDescriptions } from './components/display/Descriptions';
import { QDivider } from './components/display/Divider';
import { QEmpty } from './components/display/Empty';
import { QImage } from './components/display/Image';
import { QLazyImage } from './components/display/LazyImage';
import { QListy } from './components/display/Listy';
import { QProgressBar } from './components/display/ProgressBar';
import { QQRCode } from './components/display/QRCode';
import { QResult } from './components/display/Result';
import { QScrollNotice } from './components/display/ScrollNotice';
import { QSegmented } from './components/display/Segmented';
import { QStatistic } from './components/display/Statistic';
import { QTable } from './components/display/Table';
import { QTimeline } from './components/display/Timeline';
import { QTour } from './components/display/Tour';
import { QWatermark } from './components/display/Watermark';
import { QFormButton } from './components/form/FormButton';
import { QFormCheckboxGroup } from './components/form/FormCheckboxGroup';
import { QFormColorPicker } from './components/form/FormColorPicker';
import { QFormDatePicker } from './components/form/FormDatePicker';
import { QFormFileUpload } from './components/form/FormFileUpload';
import { QFormRadioGroup } from './components/form/FormRadioGroup';
import { QFormRangeSlider } from './components/form/FormRangeSlider';
import { QFormSelect } from './components/form/FormSelect';
import { QFormSwitch } from './components/form/FormSwitch';
import { QFormTable } from './components/form/FormTable';
import { QFormText } from './components/form/FormText';
import { QFormTextarea } from './components/form/FormTextarea';
import { QForm } from './components/form/QForm';
import { QFormItem } from './components/form/QFormItem';
import { QSearch } from './components/form/Search';
import { QAutoComplete } from './components/input/AutoComplete';
import { QCascader } from './components/input/Cascader';
import { QInputNumber } from './components/input/InputNumber';
import { QMentions } from './components/input/Mentions';
import { QRate } from './components/input/Rate';
import { QSlider } from './components/input/Slider';
import { QTimePicker } from './components/input/TimePicker';
import { QTransfer } from './components/input/Transfer';
import { QTreeSelect } from './components/input/TreeSelect';
import { QAffix } from './components/layout/Affix';
import { QCard } from './components/layout/Card';
import { QCol } from './components/layout/Col';
import { QCollapse } from './components/layout/Collapse';
import { QCollapseItem } from './components/layout/CollapseItem';
import { QCollapsibleSection } from './components/layout/CollapsibleSection';
import { QContent } from './components/layout/Content';
import { QDialog } from './components/layout/Dialog';
import { QDrawer } from './components/layout/Drawer';
import { QFlex } from './components/layout/Flex';
import { QFooter } from './components/layout/Footer';
import { QHeader } from './components/layout/Header';
import { QLayout } from './components/layout/Layout';
import { QMasonry } from './components/layout/Masonry';
import { QPopconfirm } from './components/layout/Popconfirm';
import { QPopContainer } from './components/layout/PopContainer';
import { QPopover } from './components/layout/Popover';
import { QRow } from './components/layout/Row';
import { QScrollContainer } from './components/layout/ScrollContainer';
import { QSider } from './components/layout/Sider';
import { QSpace } from './components/layout/Space';
import { QSplitter } from './components/layout/Splitter';
import { QSwiperAction } from './components/layout/SwiperAction';
import { QTooltip } from './components/layout/Tooltip';
import { QTree } from './components/layout/Tree';
import { QTreeNode } from './components/layout/TreeNode';
import {
  QBreathing,
  QSkeleton,
  QSpinner,
} from './components/loading/animations';
import { QLoading } from './components/loading/Loading';
import { QAnchor } from './components/navigation/Anchor';
import { QBreadcrumb } from './components/navigation/Breadcrumb';
import { QDropdown } from './components/navigation/Dropdown';
import { QMenu } from './components/navigation/Menu';
import { QNavSection } from './components/navigation/NavSection';
import { QSteps } from './components/navigation/Steps';
import { QTab } from './components/navigation/Tab';
import { QApp } from './components/theme/App';
import { QConfigProvider } from './components/theme/ConfigProvider';
import { QThemeToggle } from './components/theme/ThemeToggle';

/**
 * 全局注册所有组件
 * @description 独立入口，避免在 `qyani-components` 主入口引入全部组件。
 * QMarkdownRender 体积较大（依赖 marked/highlight.js 等），不在此注册，请按需引入。
 * 使用方式：`import install from 'qyani-components/install'; app.use(install);`
 * @param app Vue 应用实例
 */
export function install(app: App) {
  app.component('QButton', QButton);
  app.component('QFloatButton', QFloatButton);
  app.component('QIcon', QIcon);
  app.component('QMessage', QMessage);
  app.component('QNotification', QNotification);
  app.component('QPagination', QPagination);
  app.component('QTag', QTag);
  app.component('QTypography', QTypography);
  app.component('QAlert', QAlert);
  app.component('QAvatar', QAvatar);
  app.component('QBadge', QBadge);
  app.component('QBorderBeam', QBorderBeam);
  app.component('QCalendar', QCalendar);
  app.component('QCarousel', QCarousel);
  app.component('QCarouselItem', QCarouselItem);
  app.component('QDescriptions', QDescriptions);
  app.component('QDivider', QDivider);
  app.component('QEmpty', QEmpty);
  app.component('QImage', QImage);
  app.component('QLazyImage', QLazyImage);
  app.component('QListy', QListy);
  app.component('QProgressBar', QProgressBar);
  app.component('QQRCode', QQRCode);
  app.component('QResult', QResult);
  app.component('QScrollNotice', QScrollNotice);
  app.component('QSegmented', QSegmented);
  app.component('QStatistic', QStatistic);
  app.component('QTable', QTable);
  app.component('QTimeline', QTimeline);
  app.component('QTour', QTour);
  app.component('QWatermark', QWatermark);
  app.component('QFormButton', QFormButton);
  app.component('QFormCheckboxGroup', QFormCheckboxGroup);
  app.component('QFormColorPicker', QFormColorPicker);
  app.component('QFormDatePicker', QFormDatePicker);
  app.component('QFormFileUpload', QFormFileUpload);
  app.component('QFormRadioGroup', QFormRadioGroup);
  app.component('QFormRangeSlider', QFormRangeSlider);
  app.component('QFormSelect', QFormSelect);
  app.component('QFormSwitch', QFormSwitch);
  app.component('QFormTable', QFormTable);
  app.component('QFormText', QFormText);
  app.component('QFormTextarea', QFormTextarea);
  app.component('QSearch', QSearch);
  app.component('QForm', QForm);
  app.component('QFormItem', QFormItem);
  app.component('QAutoComplete', QAutoComplete);
  app.component('QCascader', QCascader);
  app.component('QInputNumber', QInputNumber);
  app.component('QMentions', QMentions);
  app.component('QRate', QRate);
  app.component('QSlider', QSlider);
  app.component('QTimePicker', QTimePicker);
  app.component('QTransfer', QTransfer);
  app.component('QTreeSelect', QTreeSelect);
  app.component('QAffix', QAffix);
  app.component('QCard', QCard);
  app.component('QCol', QCol);
  app.component('QCollapse', QCollapse);
  app.component('QCollapseItem', QCollapseItem);
  app.component('QCollapsibleSection', QCollapsibleSection);
  app.component('QDialog', QDialog);
  app.component('QDrawer', QDrawer);
  app.component('QFlex', QFlex);
  app.component('QFooter', QFooter);
  app.component('QHeader', QHeader);
  app.component('QContent', QContent);
  app.component('QLayout', QLayout);
  app.component('QMasonry', QMasonry);
  app.component('QPopContainer', QPopContainer);
  app.component('QPopconfirm', QPopconfirm);
  app.component('QPopover', QPopover);
  app.component('QRow', QRow);
  app.component('QScrollContainer', QScrollContainer);
  app.component('QSider', QSider);
  app.component('QSpace', QSpace);
  app.component('QSplitter', QSplitter);
  app.component('QSwiperAction', QSwiperAction);
  app.component('QTooltip', QTooltip);
  app.component('QTree', QTree);
  app.component('QTreeNode', QTreeNode);
  app.component('QLoading', QLoading);
  app.component('QBreathing', QBreathing);
  app.component('QSkeleton', QSkeleton);
  app.component('QSpinner', QSpinner);
  app.component('QAnchor', QAnchor);
  app.component('QBreadcrumb', QBreadcrumb);
  app.component('QDropdown', QDropdown);
  app.component('QMenu', QMenu);
  app.component('QNavSection', QNavSection);
  app.component('QSteps', QSteps);
  app.component('QTab', QTab);
  app.component('QApp', QApp);
  app.component('QConfigProvider', QConfigProvider);
  app.component('QThemeToggle', QThemeToggle);
}

export default install;
