export interface ComponentInfo {
  category: string;
  name: string;
  displayName: string;
  docPath: string;
}
export const useComponentInfo: ComponentInfo[] = [
  {
    name: 'Icon',
    displayName: 'Icon',
    category: '/components/basic/',
    docPath: '/docs/components/basic/Icon.md',
  },
  {
    name: 'Message',
    displayName: 'Message',
    category: '/components/basic/',
    docPath: '/docs/components/basic/Message.md',
  },
  {
    name: 'Pagination',
    displayName: 'Pagination',
    category: '/components/basic/',
    docPath: '/docs/components/basic/Pagination.md',
  },
  {
    name: 'Tag',
    displayName: 'Tag',
    category: '/components/basic/',
    docPath: '/docs/components/basic/Tag.md',
  },
  {
    name: 'Avatar',
    displayName: 'Avatar',
    category: '/components/display/',
    docPath: '/docs/components/display/Avatar.md',
  },
  {
    name: 'Badge',
    displayName: 'Badge',
    category: '/components/display/',
    docPath: '/docs/components/display/Badge.md',
  },
  {
    name: 'Carousel',
    displayName: 'Carousel',
    category: '/components/display/',
    docPath: '/docs/components/display/Carousel.md',
  },
  {
    name: 'CarouselItem',
    displayName: 'CarouselItem',
    category: '/components/display/',
    docPath: '/docs/components/display/CarouselItem.md',
  },
  {
    name: 'Divider',
    displayName: 'Divider',
    category: '/components/display/',
    docPath: '/docs/components/display/Divider.md',
  },
  {
    name: 'LazyImage',
    displayName: 'LazyImage',
    category: '/components/display/',
    docPath: '/docs/components/display/LazyImage.md',
  },
  {
    name: 'MarkdownRender',
    displayName: 'MarkdownRender',
    category: '/components/display/',
    docPath: '/docs/components/display/MarkdownRender.md',
  },
  {
    name: 'ProgressBar',
    displayName: 'ProgressBar',
    category: '/components/display/',
    docPath: '/docs/components/display/ProgressBar.md',
  },
  {
    name: 'ScrollNotice',
    displayName: 'ScrollNotice',
    category: '/components/display/',
    docPath: '/docs/components/display/ScrollNotice.md',
  },
  {
    name: 'FormButton',
    displayName: 'FormButton',
    category: '/components/form/',
    docPath: '/docs/components/form/FormButton.md',
  },
  {
    name: 'FormCheckboxGroup',
    displayName: 'FormCheckboxGroup',
    category: '/components/form/',
    docPath: '/docs/components/form/FormCheckboxGroup.md',
  },
  {
    name: 'FormColorPicker',
    displayName: 'FormColorPicker',
    category: '/components/form/',
    docPath: '/docs/components/form/FormColorPicker.md',
  },
  {
    name: 'FormDatePicker',
    displayName: 'FormDatePicker',
    category: '/components/form/',
    docPath: '/docs/components/form/FormDatePicker.md',
  },
  {
    name: 'FormFileUpload',
    displayName: 'FormFileUpload',
    category: '/components/form/',
    docPath: '/docs/components/form/FormFileUpload.md',
  },
  {
    name: 'FormRadioGroup',
    displayName: 'FormRadioGroup',
    category: '/components/form/',
    docPath: '/docs/components/form/FormRadioGroup.md',
  },
  {
    name: 'FormRangeSlider',
    displayName: 'FormRangeSlider',
    category: '/components/form/',
    docPath: '/docs/components/form/FormRangeSlider.md',
  },
  {
    name: 'FormSelect',
    displayName: 'FormSelect',
    category: '/components/form/',
    docPath: '/docs/components/form/FormSelect.md',
  },
  {
    name: 'FormSwitch',
    displayName: 'FormSwitch',
    category: '/components/form/',
    docPath: '/docs/components/form/FormSwitch.md',
  },
  {
    name: 'FormTable',
    displayName: 'FormTable',
    category: '/components/form/',
    docPath: '/docs/components/form/FormTable.md',
  },
  {
    name: 'FormText',
    displayName: 'FormText',
    category: '/components/form/',
    docPath: '/docs/components/form/FormText.md',
  },
  {
    name: 'FormTextarea',
    displayName: 'FormTextarea',
    category: '/components/form/',
    docPath: '/docs/components/form/FormTextarea.md',
  },
  {
    name: 'Search',
    displayName: 'Search',
    category: '/components/form/',
    docPath: '/docs/components/form/Search.md',
  },
  {
    name: 'Card',
    displayName: 'Card',
    category: '/components/layout/',
    docPath: '/docs/components/layout/Card.md',
  },
  {
    name: 'Collapse',
    displayName: 'Collapse',
    category: '/components/layout/',
    docPath: '/docs/components/layout/Collapse.md',
  },
  {
    name: 'CollapseItem',
    displayName: 'CollapseItem',
    category: '/components/layout/',
    docPath: '/docs/components/layout/CollapseItem.md',
  },
  {
    name: 'CollapsibleSection',
    displayName: 'CollapsibleSection',
    category: '/components/layout/',
    docPath: '/docs/components/layout/CollapsibleSection.md',
  },
  {
    name: 'Dialog',
    displayName: 'Dialog',
    category: '/components/layout/',
    docPath: '/docs/components/layout/Dialog.md',
  },
  {
    name: 'Drawer',
    displayName: 'Drawer',
    category: '/components/layout/',
    docPath: '/docs/components/layout/Drawer.md',
  },
  {
    name: 'PopContainer',
    displayName: 'PopContainer',
    category: '/components/layout/',
    docPath: '/docs/components/layout/PopContainer.md',
  },
  {
    name: 'ScrollContainer',
    displayName: 'ScrollContainer',
    category: '/components/layout/',
    docPath: '/docs/components/layout/ScrollContainer.md',
  },
  {
    name: 'SwiperAction',
    displayName: 'SwiperAction',
    category: '/components/layout/',
    docPath: '/docs/components/layout/SwiperAction.md',
  },
  {
    name: 'Tree',
    displayName: 'Tree',
    category: '/components/layout/',
    docPath: '/docs/components/layout/Tree.md',
  },
  {
    name: 'TreeNode',
    displayName: 'TreeNode',
    category: '/components/layout/',
    docPath: '/docs/components/layout/TreeNode.md',
  },
  {
    name: 'Loading',
    displayName: 'Loading',
    category: '/components/loading/',
    docPath: '/docs/components/loading/Loading.md',
  },
  {
    name: 'Breathing',
    displayName: 'Breathing',
    category: '/components/loading/animations/',
    docPath: '/docs/components/loading/animations/Breathing.md',
  },
  {
    name: 'Skeleton',
    displayName: 'Skeleton',
    category: '/components/loading/animations/',
    docPath: '/docs/components/loading/animations/Skeleton.md',
  },
  {
    name: 'Spinner',
    displayName: 'Spinner',
    category: '/components/loading/animations/',
    docPath: '/docs/components/loading/animations/Spinner.md',
  },
  {
    name: 'NavSection',
    displayName: 'NavSection',
    category: '/components/navigation/',
    docPath: '/docs/components/navigation/NavSection.md',
  },
  {
    name: 'Tab',
    displayName: 'Tab',
    category: '/components/navigation/',
    docPath: '/docs/components/navigation/Tab.md',
  },
  {
    name: 'ThemeToggle',
    displayName: 'ThemeToggle',
    category: '/components/theme/',
    docPath: '/docs/components/theme/ThemeToggle.md',
  },
  {
    name: 'useDrag',
    displayName: 'useDrag',
    category: '/events/',
    docPath: '/docs/events/useDrag.md',
  },
  {
    name: 'useFormEvents',
    displayName: 'useFormEvents',
    category: '/events/',
    docPath: '/docs/events/useFormEvents.md',
  },
  {
    name: 'useMousePosition',
    displayName: 'useMousePosition',
    category: '/events/',
    docPath: '/docs/events/useMousePosition.md',
  },
  {
    name: 'useArray',
    displayName: 'useArray',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useArray.md',
  },
  {
    name: 'useAVLTree',
    displayName: 'useAVLTree',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useAVLTree.md',
  },
  {
    name: 'useGraph',
    displayName: 'useGraph',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useGraph.md',
  },
  {
    name: 'useHeap',
    displayName: 'useHeap',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useHeap.md',
  },
  {
    name: 'useRedBlackTree',
    displayName: 'useRedBlackTree',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useRedBlackTree.md',
  },
  {
    name: 'useSegmentTree',
    displayName: 'useSegmentTree',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useSegmentTree.md',
  },
  {
    name: 'useSkipList',
    displayName: 'useSkipList',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useSkipList.md',
  },
  {
    name: 'useSort',
    displayName: 'useSort',
    category: '/utils/algorithm/',
    docPath: '/docs/utils/algorithm/useSort.md',
  },
  {
    name: 'useClip',
    displayName: 'useClip',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useClip.md',
  },
  {
    name: 'useDebounce',
    displayName: 'useDebounce',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useDebounce.md',
  },
  {
    name: 'useFollowSystemTheme',
    displayName: 'useFollowSystemTheme',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useFollowSystemTheme.md',
  },
  {
    name: 'useLocalStorage',
    displayName: 'useLocalStorage',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useLocalStorage.md',
  },
  {
    name: 'useLRUCache',
    displayName: 'useLRUCache',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useLRUCache.md',
  },
  {
    name: 'useMemoryCache',
    displayName: 'useMemoryCache',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useMemoryCache.md',
  },
  {
    name: 'useMessage',
    displayName: 'useMessage',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useMessage.md',
  },
  {
    name: 'useNullHandel',
    displayName: 'useNullHandel',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useNullHandel.md',
  },
  {
    name: 'useScreenSize',
    displayName: 'useScreenSize',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useScreenSize.md',
  },
  {
    name: 'useShowLoading',
    displayName: 'useShowLoading',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useShowLoading.md',
  },
  {
    name: 'useThrottle',
    displayName: 'useThrottle',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useThrottle.md',
  },
  {
    name: 'useTimeDisplay',
    displayName: 'useTimeDisplay',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useTimeDisplay.md',
  },
  {
    name: 'useTimeUtils',
    displayName: 'useTimeUtils',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useTimeUtils.md',
  },
  {
    name: 'useWindowResize',
    displayName: 'useWindowResize',
    category: '/utils/business/',
    docPath: '/docs/utils/business/useWindowResize.md',
  },
];
