export interface DocsEntry {
  category: string[];
  demoPath?: string;
  displayName: string;
  docPath: string;
  name: string;
  packageName: string;
}

export const docsEntries: DocsEntry[] = [
  {
    name: 'useDrag',
    displayName: 'useDrag',
    category: ['Browser Utilities', 'Events'],
    docPath: '/docs/events/useDrag.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useFormEvents',
    displayName: 'useFormEvents',
    category: ['Browser Utilities', 'Events'],
    docPath: '/docs/events/useFormEvents.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useMousePosition',
    displayName: 'useMousePosition',
    category: ['Browser Utilities', 'Events'],
    docPath: '/docs/events/useMousePosition.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useFollowSystemTheme',
    displayName: 'useFollowSystemTheme',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useFollowSystemTheme.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useLRUCache',
    displayName: 'useLRUCache',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useLRUCache.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useLocalStorage',
    displayName: 'useLocalStorage',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useLocalStorage.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useMessage',
    displayName: 'useMessage',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useMessage.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useScreenSize',
    displayName: 'useScreenSize',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useScreenSize.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useShowLoading',
    displayName: 'useShowLoading',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useShowLoading.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useTimeDisplay',
    displayName: 'useTimeDisplay',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useTimeDisplay.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useWindowResize',
    displayName: 'useWindowResize',
    category: ['Browser Utilities', 'Utilities', 'business'],
    docPath: '/docs/utils/business/useWindowResize.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'useAVLTree',
    displayName: 'useAVLTree',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useAVLTree.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useArray',
    displayName: 'useArray',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useArray.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useGraph',
    displayName: 'useGraph',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useGraph.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useHeap',
    displayName: 'useHeap',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useHeap.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useRedBlackTree',
    displayName: 'useRedBlackTree',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useRedBlackTree.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useSegmentTree',
    displayName: 'useSegmentTree',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useSegmentTree.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useSkipList',
    displayName: 'useSkipList',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useSkipList.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useSort',
    displayName: 'useSort',
    category: ['Core', 'algorithm'],
    docPath: '/docs/core/algorithm/useSort.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useClip',
    displayName: 'useClip',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useClip.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useDebounce',
    displayName: 'useDebounce',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useDebounce.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useMemoryCache',
    displayName: 'useMemoryCache',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useMemoryCache.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useNullHandel',
    displayName: 'useNullHandel',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useNullHandel.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useObject',
    displayName: 'useObject',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useObject.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useThrottle',
    displayName: 'useThrottle',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useThrottle.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'useTimeUtils',
    displayName: 'useTimeUtils',
    category: ['Core', 'business'],
    docPath: '/docs/core/business/useTimeUtils.md',
    packageName: '@qianrenni/core',
    demoPath: null,
  },
  {
    name: 'style-base',
    displayName: '基础样式 (Base)',
    category: ['Design System'],
    docPath: '/docs/styles/base.md',
    packageName: 'qyani-components',
    demoPath: 'styles/base',
  },
  {
    name: 'style-overview',
    displayName: '设计系统总览',
    category: ['Design System'],
    docPath: '/docs/styles/overview.md',
    packageName: 'qyani-components',
    demoPath: null,
  },
  {
    name: 'style-theme',
    displayName: '主题 (Theme)',
    category: ['Design System'],
    docPath: '/docs/styles/theme.md',
    packageName: 'qyani-components',
    demoPath: 'styles/theme',
  },
  {
    name: 'style-tokens',
    displayName: '设计变量 (Tokens)',
    category: ['Design System'],
    docPath: '/docs/styles/tokens.md',
    packageName: 'qyani-components',
    demoPath: 'styles/tokens',
  },
  {
    name: 'style-utilities',
    displayName: '工具类 (Utilities)',
    category: ['Design System'],
    docPath: '/docs/styles/utilities.md',
    packageName: 'qyani-components',
    demoPath: 'styles/utilities',
  },
  {
    name: 'Button',
    displayName: 'Button',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Button.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Button',
  },
  {
    name: 'Icon',
    displayName: 'Icon',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Icon.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Icon',
  },
  {
    name: 'Message',
    displayName: 'Message',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Message.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Message',
  },
  {
    name: 'Pagination',
    displayName: 'Pagination',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Pagination.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Pagination',
  },
  {
    name: 'Tag',
    displayName: 'Tag',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Tag.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Tag',
  },
  {
    name: 'Typography',
    displayName: 'Typography',
    category: ['Vue Components', 'basic'],
    docPath: '/docs/components/basic/Typography.md',
    packageName: 'qyani-components',
    demoPath: 'components/basic/Typography',
  },
  {
    name: 'Avatar',
    displayName: 'Avatar',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Avatar.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Avatar',
  },
  {
    name: 'Badge',
    displayName: 'Badge',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Badge.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Badge',
  },
  {
    name: 'Carousel',
    displayName: 'Carousel',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Carousel.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Carousel',
  },
  {
    name: 'CarouselItem',
    displayName: 'CarouselItem',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/CarouselItem.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/CarouselItem',
  },
  {
    name: 'Divider',
    displayName: 'Divider',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Divider.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Divider',
  },
  {
    name: 'Empty',
    displayName: 'Empty',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Empty.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Empty',
  },
  {
    name: 'LazyImage',
    displayName: 'LazyImage',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/LazyImage.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/LazyImage',
  },
  {
    name: 'MarkdownRender',
    displayName: 'MarkdownRender',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/MarkdownRender.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/MarkdownRender',
  },
  {
    name: 'ProgressBar',
    displayName: 'ProgressBar',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/ProgressBar.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/ProgressBar',
  },
  {
    name: 'ScrollNotice',
    displayName: 'ScrollNotice',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/ScrollNotice.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/ScrollNotice',
  },
  {
    name: 'Segmented',
    displayName: 'Segmented',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Segmented.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Segmented',
  },
  {
    name: 'Statistic',
    displayName: 'Statistic',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Statistic.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Statistic',
  },
  {
    name: 'Timeline',
    displayName: 'Timeline',
    category: ['Vue Components', 'display'],
    docPath: '/docs/components/display/Timeline.md',
    packageName: 'qyani-components',
    demoPath: 'components/display/Timeline',
  },
  {
    name: 'FormButton',
    displayName: 'FormButton',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormButton.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormButton',
  },
  {
    name: 'FormCheckboxGroup',
    displayName: 'FormCheckboxGroup',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormCheckboxGroup.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormCheckboxGroup',
  },
  {
    name: 'FormColorPicker',
    displayName: 'FormColorPicker',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormColorPicker.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormColorPicker',
  },
  {
    name: 'FormDatePicker',
    displayName: 'FormDatePicker',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormDatePicker.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormDatePicker',
  },
  {
    name: 'FormFileUpload',
    displayName: 'FormFileUpload',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormFileUpload.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormFileUpload',
  },
  {
    name: 'FormRadioGroup',
    displayName: 'FormRadioGroup',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormRadioGroup.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormRadioGroup',
  },
  {
    name: 'FormRangeSlider',
    displayName: 'FormRangeSlider',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormRangeSlider.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormRangeSlider',
  },
  {
    name: 'FormSelect',
    displayName: 'FormSelect',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormSelect.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormSelect',
  },
  {
    name: 'FormSwitch',
    displayName: 'FormSwitch',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormSwitch.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormSwitch',
  },
  {
    name: 'FormTable',
    displayName: 'FormTable',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormTable.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormTable',
  },
  {
    name: 'FormText',
    displayName: 'FormText',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormText.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormText',
  },
  {
    name: 'FormTextarea',
    displayName: 'FormTextarea',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/FormTextarea.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/FormTextarea',
  },
  {
    name: 'Search',
    displayName: 'Search',
    category: ['Vue Components', 'form'],
    docPath: '/docs/components/form/Search.md',
    packageName: 'qyani-components',
    demoPath: 'components/form/Search',
  },
  {
    name: 'AutoComplete',
    displayName: 'AutoComplete',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/AutoComplete.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/AutoComplete',
  },
  {
    name: 'Cascader',
    displayName: 'Cascader',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/Cascader.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/Cascader',
  },
  {
    name: 'InputNumber',
    displayName: 'InputNumber',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/InputNumber.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/InputNumber',
  },
  {
    name: 'Rate',
    displayName: 'Rate',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/Rate.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/Rate',
  },
  {
    name: 'Slider',
    displayName: 'Slider',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/Slider.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/Slider',
  },
  {
    name: 'Transfer',
    displayName: 'Transfer',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/Transfer.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/Transfer',
  },
  {
    name: 'TreeSelect',
    displayName: 'TreeSelect',
    category: ['Vue Components', 'input'],
    docPath: '/docs/components/input/TreeSelect.md',
    packageName: 'qyani-components',
    demoPath: 'components/input/TreeSelect',
  },
  {
    name: 'Card',
    displayName: 'Card',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Card.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Card',
  },
  {
    name: 'Col',
    displayName: 'Col',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Col.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Col',
  },
  {
    name: 'Collapse',
    displayName: 'Collapse',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Collapse.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Collapse',
  },
  {
    name: 'CollapseItem',
    displayName: 'CollapseItem',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/CollapseItem.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/CollapseItem',
  },
  {
    name: 'CollapsibleSection',
    displayName: 'CollapsibleSection',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/CollapsibleSection.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/CollapsibleSection',
  },
  {
    name: 'Content',
    displayName: 'Content',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Content.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Content',
  },
  {
    name: 'Dialog',
    displayName: 'Dialog',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Dialog.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Dialog',
  },
  {
    name: 'Drawer',
    displayName: 'Drawer',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Drawer.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Drawer',
  },
  {
    name: 'Footer',
    displayName: 'Footer',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Footer.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Footer',
  },
  {
    name: 'Header',
    displayName: 'Header',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Header.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Header',
  },
  {
    name: 'Layout',
    displayName: 'Layout',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Layout.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Layout',
  },
  {
    name: 'PopContainer',
    displayName: 'PopContainer',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/PopContainer.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/PopContainer',
  },
  {
    name: 'Row',
    displayName: 'Row',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Row.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Row',
  },
  {
    name: 'ScrollContainer',
    displayName: 'ScrollContainer',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/ScrollContainer.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/ScrollContainer',
  },
  {
    name: 'Sider',
    displayName: 'Sider',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Sider.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Sider',
  },
  {
    name: 'Space',
    displayName: 'Space',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Space.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Space',
  },
  {
    name: 'SwiperAction',
    displayName: 'SwiperAction',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/SwiperAction.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/SwiperAction',
  },
  {
    name: 'Tooltip',
    displayName: 'Tooltip',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Tooltip.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Tooltip',
  },
  {
    name: 'Tree',
    displayName: 'Tree',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/Tree.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/Tree',
  },
  {
    name: 'TreeNode',
    displayName: 'TreeNode',
    category: ['Vue Components', 'layout'],
    docPath: '/docs/components/layout/TreeNode.md',
    packageName: 'qyani-components',
    demoPath: 'components/layout/TreeNode',
  },
  {
    name: 'Loading',
    displayName: 'Loading',
    category: ['Vue Components', 'loading'],
    docPath: '/docs/components/loading/Loading.md',
    packageName: 'qyani-components',
    demoPath: 'components/loading/Loading',
  },
  {
    name: 'Breathing',
    displayName: 'Breathing',
    category: ['Vue Components', 'loading', 'animations'],
    docPath: '/docs/components/loading/animations/Breathing.md',
    packageName: 'qyani-components',
    demoPath: 'components/loading/animations/Breathing',
  },
  {
    name: 'Skeleton',
    displayName: 'Skeleton',
    category: ['Vue Components', 'loading', 'animations'],
    docPath: '/docs/components/loading/animations/Skeleton.md',
    packageName: 'qyani-components',
    demoPath: 'components/loading/animations/Skeleton',
  },
  {
    name: 'Spinner',
    displayName: 'Spinner',
    category: ['Vue Components', 'loading', 'animations'],
    docPath: '/docs/components/loading/animations/Spinner.md',
    packageName: 'qyani-components',
    demoPath: 'components/loading/animations/Spinner',
  },
  {
    name: 'Anchor',
    displayName: 'Anchor',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Anchor.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Anchor',
  },
  {
    name: 'Breadcrumb',
    displayName: 'Breadcrumb',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Breadcrumb.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Breadcrumb',
  },
  {
    name: 'Dropdown',
    displayName: 'Dropdown',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Dropdown.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Dropdown',
  },
  {
    name: 'Menu',
    displayName: 'Menu',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Menu.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Menu',
  },
  {
    name: 'NavSection',
    displayName: 'NavSection',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/NavSection.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/NavSection',
  },
  {
    name: 'Steps',
    displayName: 'Steps',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Steps.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Steps',
  },
  {
    name: 'Tab',
    displayName: 'Tab',
    category: ['Vue Components', 'navigation'],
    docPath: '/docs/components/navigation/Tab.md',
    packageName: 'qyani-components',
    demoPath: 'components/navigation/Tab',
  },
  {
    name: 'ThemeToggle',
    displayName: 'ThemeToggle',
    category: ['Vue Components', 'theme'],
    docPath: '/docs/components/theme/ThemeToggle.md',
    packageName: 'qyani-components',
    demoPath: 'components/theme/ThemeToggle',
  },
] as DocsEntry[];
